const CACHE_NAME = 'english30-v13';
const ASSETS = ["./app.js",
  "./assessments.js",
  "./child-ux.css",
  "./child-ux.js",
  "./content/assessment-entrance.json",
  "./content/assessment-final.json",
  "./content/day-01.json",
  "./content/day-02.json",
  "./content/day-03.json",
  "./content/day-04.json",
  "./content/day-05.json",
  "./content/day-06.json",
  "./content/day-07.json",
  "./content/day-08.json",
  "./content/day-09.json",
  "./content/day-10.json",
  "./content/day-11.json",
  "./content/day-12.json",
  "./content/day-13.json",
  "./content/day-14.json",
  "./content/day-15.json",
  "./content/day-16.json",
  "./content/day-17.json",
  "./content/day-18.json",
  "./content/day-19.json",
  "./content/day-20.json",
  "./content/day-21.json",
  "./content/day-22.json",
  "./content/day-23.json",
  "./content/day-24.json",
  "./content/day-25.json",
  "./content/day-26.json",
  "./content/day-27.json",
  "./content/day-28.json",
  "./content/day-29.json",
  "./content/day-30.json",
  "./data.js",
  "./icon-192.png",
  "./icon-512.png",
  "./manifest.json",
  "./parent-dashboard.css",
  "./parent-dashboard.js",
  "./shadowing.css",
  "./shadowing.js",
  "./storage.js",
  "./speech-pending.js",
  "./styles.css",
  "./sw.js",
  "./tts-controller.css",
  "./tts-controller.js",
  "./typing-dictation.css",
  "./typing-dictation.js",
  "./update.js",
  "./vocab-speaking.css",
  "./vocab-speaking.js"];
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS))); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('english30-') && key !== CACHE_NAME).map(key => caches.delete(key)))).then(() => self.clients.claim())); });
self.addEventListener('message', event => { if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting(); });
self.addEventListener('fetch', event => { if (event.request.method !== 'GET') return; if (event.request.mode === 'navigate') { event.respondWith(fetch(event.request).then(response => { const copy=response.clone(); caches.open(CACHE_NAME).then(cache => cache.put(event.request,copy)); return response; }).catch(() => caches.match("../index.html"))); return; } event.respondWith(caches.match(event.request).then(cached => cached || fetch(event.request).then(response => { if (response.ok) { const copy=response.clone(); caches.open(CACHE_NAME).then(cache => cache.put(event.request,copy)); } return response; }))); });
